image: "ruby:latest"

before_script:
  - bundle install

test:
  coverage: "/\(\d+.\d+\%\) covered/"
  script: bundle exec theorize -d tests
  artifacts:
    reports:
      cobertura: coverage/coverage.xml