image: "ruby:latest"

before_script:
  - bundle install

test:
  script: bundle exec ruby tests/arrangment.rb
  artifacts:
    reports:
      cobertura: coverage/coverage.xml
  coverage: '/\(\d+.\d+\%\) covered/'
